[unstable]
build-std = ["core", "compiler_builtins","alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target-dir = "target"

[target.x86_64-unknown-uefi]
rustflags = ["-C", "llvm-args=-disable-loop-idiom-wcslen"]
