[package]
name = "bootloader"
version = "0.1.0"
edition = "2024"
authors = ["nfge Github: <https://github.com/nfge>"]

[dependencies]
uefi = "0.37.0"
uefi-raw = "0.13.0"
bootinfo= {path = "../common/bootinfo"}
elf_headers = {path = "../common/elf_headers"}
[[bin]]
name = "bootloader"
test=false
bench=false