name: Build-ISO

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: |
        rustup toolchain install nightly
        rustup default nightly
        rustup component add rust-src --toolchain nightly
        rustup target add x86_64-unknown-uefi
        sudo apt install dosfstools mtools xorriso
    - name: Build
      run: |
        cargo +nightly build -Z json-target-spec -p kernel --target x86_64.json --release
        RUSTFLAGS="-C llvm-args=-disable-loop-idiom-wcslen" cargo build -p bootloader --target x86_64-unknown-uefi --release
    - name: Prepare artifacts
      run: |
        mkdir out
        mkdir -p out/EFI/BOOT/
        mkdir -p out/EFI/Roselia/
        cp -r target/x86_64/release/kernel out/kernel.elf
        cp -r target/x86_64-unknown-uefi/release/bootloader.efi out/EFI/BOOT/BOOTX64.efi
        cp -r target/x86_64-unknown-uefi/release/bootloader.efi out/EFI/Roselia/boot.efi
    - name: Create EFI image
      run: |
        dd if=/dev/zero of=efiboot.img bs=1M count=64

        mkfs.fat -F32 efiboot.img

        mmd -i efiboot.img ::/EFI
        mmd -i efiboot.img ::/EFI/BOOT
        mmd -i efiboot.img ::/EFI/Roselia

        mcopy -i efiboot.img out/EFI/BOOT/BOOTX64.efi ::/EFI/BOOT/
        mcopy -i efiboot.img out/EFI/Roselia/boot.efi ::/EFI/Roselia/
        mcopy -i efiboot.img out/kernel.elf ::/
        mkdir iso
        cp -r out/* iso/
        cp efiboot.img iso/
        fsck.fat -vn efiboot.img
    - name: Build ISO
      run: |
        xorriso -as mkisofs \
          -R -J \
          -V Roselia \
          -eltorito-alt-boot \
          -e efiboot.img \
          -no-emul-boot \
          -o Roselia.iso \
          iso/
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Roselia
        path: Roselia.iso