name: Build-ISO

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: |
        # rustup toolchain install nightly-2026-01-05
        rustup component add rust-src --toolchain nightly
        rustup target add x86_64-unknown-uefi
        sudo apt install xorriso
    - name: Build
      run: |
        cargo +nightly-2026-01-05 build -Z json-target-spec -p kernel --target x86_64.json --release
        cargo build -p bootloader --target x86_64-unknown-uefi --release
    - name: Prepare artifacts
      run: |
        mkdir out
        mkdir -p out/EFI/BOOT/
        mkdir -p out/EFI/Roselia/
        cp -r target/x86_64/release/kernel out/kernel.elf
        cp -r target/x86_64-unknown-uefi/release/bootloader.efi out/EFI/BOOT/BOOTX64.efi
        cp -r target/x86_64-unknown-uefi/release/bootloader.efi out/EFI/Roselia/boot.efi
    - name: Build ISO
      run: |
        xorriso -as mkisofs \
        -R -J \
        --efi-boot out/EFI/BOOT/BOOTX64.efi \
        -efi-boot-part \
        --efi-boot-image \
        --protective-msdos-label \
        out/ \
        -o roselia.iso
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Roselia
        path: roselia.iso
          
