name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: |
        rustup toolchain install nightly
        rustup component add rust-src --toolchain nightly
        rustup target add x86_64-unknown-uefi
    - name: Build
      run: |
        cargo +nightly build -Z json-target-spec -p kernel --target x86_64.json --release
        cargo build -p bootloader --target x86_64-unknown-uefi --release
    - name: Prepare artifacts
      run: |
        mkdir out
        mkdir -p out/EFI/BOOT/
        cp -r target/x86_64/release/kernel out/kernel.elf
        cp -r target/x86_64-unknown-uefi/release/bootloader.efi out/EFI/BOOT/BOOTX64.efi
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Roselia
        path: out/
          
